/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiskCityRouteImport } from './routes/risk.$city'
import { Route as SentinelCityRouteImport } from './routes/sentinel.$city'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskCityRoute = RiskCityRouteImport.update({
  id: '/risk/$city',
  path: '/risk/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const SentinelCityRoute = SentinelCityRouteImport.update({
  id: '/sentinel/$city',
  path: '/sentinel/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/risk/$city': typeof RiskCityRoute
  '/sentinel/$city': typeof SentinelCityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/risk/$city': typeof RiskCityRoute
  '/sentinel/$city': typeof SentinelCityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/risk/$city': typeof RiskCityRoute
  '/sentinel/$city': typeof SentinelCityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/risk/$city' | '/sentinel/$city'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/risk/$city' | '/sentinel/$city'
  id: '__root__' | '/' | '/risk/$city' | '/sentinel/$city'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RiskCityRoute: typeof RiskCityRoute
  SentinelCityRoute: typeof SentinelCityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk/$city': {
      id: '/risk/$city'
      path: '/risk/$city'
      fullPath: '/risk/$city'
      preLoaderRoute: typeof RiskCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentinel/$city': {
      id: '/sentinel/$city'
      path: '/sentinel/$city'
      fullPath: '/sentinel/$city'
      preLoaderRoute: typeof SentinelCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RiskCityRoute: RiskCityRoute,
  SentinelCityRoute: SentinelCityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
